# Site settings
title: Kobol Blog
header-img: img/home-bg.jpg
email: contact@kobol.io
copyright_name: Kobol Innovations Pte. Ltd.
description: "Kobol Blog. The Open Source NAS"
url: "https://blog.kobol.io"
github_username: helios-4
facebook_username: kobol.io
twitter_username: kobol_io
newsletter_subscribe: "https://kobol.io/helios4/subscribe.html"
comments: true

# Google Analytics
google_tracking_id: UA-96982596-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","Gemfile*"]

plugins: [jekyll-paginate, jekyll-feed]
